name: dep2nix
version: '0.1.0.0'
category: Web
author: John Children
maintainer: example@example.com
copyright: 2017 John Children
license: BSD3
github: githubuser/dep2nix
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
  - data-fix
  - text
  - containers
  - unordered-containers
  - vector
  - parsec
  - htoml >= 1.0 && < 1.1
  - hnix >= 0.3 && < 0.4
executables:
  dep2nix-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - dep2nix
    - text
tests:
  dep2nix-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - dep2nix
